name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19' ]
        os: [ 'windows', 'linux', 'darwin' ]
        arch: [ 'amd64' ]
    name: Go ${{ matrix.go }}-${{ matrix.os }}-${{ matrix.arch }} build
    steps:
      - uses: actions/checkout@master
      - uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
          go_version: ${{ matrix.go }}
      - run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v .
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19' ]
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@master
      - uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
          go_version: ${{ matrix.go }}
      - run: go test -v .
