name: Test, Release Tag, Update Changelog
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Go test
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: cd v2 && go test ./...
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: ./version.json
          release-count: 0